name: Cross-platform Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    name: Build for Linux, Windows, and macOS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Binaries
        run: |
          mkdir dist
          GOOS=linux GOARCH=amd64 go build -o dist/fishbot-linux-amd64 main.go
          GOOS=windows GOARCH=amd64 go build -o dist/fishbot-windows-amd64.exe main.go
          GOOS=darwin GOARCH=amd64 go build -o dist/fishbot-macos-amd64 main.go

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/fishbot-linux-amd64
            dist/fishbot-windows-amd64.exe
            dist/fishbot-macos-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
